//
//  NutritionTargets.swift
//  FoodShutter
//
//  Data models for nutrition targets generated by Gemini Planner
//

import Foundation

// MARK: - API Response Models

/// API response model from Gemini Nutrition Planner
struct NutritionTargetsResult: Codable {
    let dailyCalories: NutrientRange
    let dailyProtein: NutrientRange
    let dailyFat: NutrientRange
    let dailyCarbohydrate: NutrientRange
    let explanation: String

    enum CodingKeys: String, CodingKey {
        case dailyCalories = "daily_calories"
        case dailyProtein = "daily_protein"
        case dailyFat = "daily_fat"
        case dailyCarbohydrate = "daily_carbohydrate"
        case explanation
    }
}

/// Represents a nutrient range with min/max/target values
struct NutrientRange: Codable {
    let min: Double
    let max: Double
    let target: Double
}

// MARK: - UI Model

/// UI model for nutrition targets with helper methods
struct NutritionTargets: Codable {
    // Calories
    let caloriesMin: Double
    let caloriesMax: Double
    let caloriesTarget: Double

    // Protein (grams)
    let proteinMin: Double
    let proteinMax: Double
    let proteinTarget: Double

    // Fat (grams)
    let fatMin: Double
    let fatMax: Double
    let fatTarget: Double

    // Carbohydrates (grams)
    let carbMin: Double
    let carbMax: Double
    let carbTarget: Double

    // Metadata
    let explanation: String
    let generatedDate: Date

    /// Initialize with all parameters (for testing and manual creation)
    init(
        caloriesMin: Double,
        caloriesMax: Double,
        caloriesTarget: Double,
        proteinMin: Double,
        proteinMax: Double,
        proteinTarget: Double,
        fatMin: Double,
        fatMax: Double,
        fatTarget: Double,
        carbMin: Double,
        carbMax: Double,
        carbTarget: Double,
        explanation: String,
        generatedDate: Date
    ) {
        self.caloriesMin = caloriesMin
        self.caloriesMax = caloriesMax
        self.caloriesTarget = caloriesTarget
        self.proteinMin = proteinMin
        self.proteinMax = proteinMax
        self.proteinTarget = proteinTarget
        self.fatMin = fatMin
        self.fatMax = fatMax
        self.fatTarget = fatTarget
        self.carbMin = carbMin
        self.carbMax = carbMax
        self.carbTarget = carbTarget
        self.explanation = explanation
        self.generatedDate = generatedDate
    }

    /// Initialize from API response
    init(from result: NutritionTargetsResult) {
        self.caloriesMin = result.dailyCalories.min
        self.caloriesMax = result.dailyCalories.max
        self.caloriesTarget = result.dailyCalories.target

        self.proteinMin = result.dailyProtein.min
        self.proteinMax = result.dailyProtein.max
        self.proteinTarget = result.dailyProtein.target

        self.fatMin = result.dailyFat.min
        self.fatMax = result.dailyFat.max
        self.fatTarget = result.dailyFat.target

        self.carbMin = result.dailyCarbohydrate.min
        self.carbMax = result.dailyCarbohydrate.max
        self.carbTarget = result.dailyCarbohydrate.target

        self.explanation = result.explanation
        self.generatedDate = Date()
    }

    // MARK: - Range Checking Methods

    /// Check if calories value is within target range
    func isCaloriesInRange(_ value: Double) -> Bool {
        value >= caloriesMin && value <= caloriesMax
    }

    /// Check if protein value is within target range
    func isProteinInRange(_ value: Double) -> Bool {
        value >= proteinMin && value <= proteinMax
    }

    /// Check if fat value is within target range
    func isFatInRange(_ value: Double) -> Bool {
        value >= fatMin && value <= fatMax
    }

    /// Check if carbohydrate value is within target range
    func isCarbInRange(_ value: Double) -> Bool {
        value >= carbMin && value <= carbMax
    }

    /// Check if all nutrients are within their respective ranges
    /// Used by trophy system to determine if day meets all goals
    func isAllNutrientsInRange(calories: Double, protein: Double, fat: Double, carb: Double) -> Bool {
        isCaloriesInRange(calories) &&
        isProteinInRange(protein) &&
        isFatInRange(fat) &&
        isCarbInRange(carb)
    }
}
