"""
Compare Qwen3.5 (base + fine-tuned) vs Gemini-2.0-Flash on the same 50 test samples.
Reads inference_results.json generated by visualize.py — no need to re-run Qwen.

Usage:
    export GOOGLE_API_KEY="your_key"
    python compare_gemini.py
"""

import json
import os
import time
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
from difflib import SequenceMatcher
from tqdm import tqdm

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import google.generativeai as genai

# ── Config ───────────────────────────────────────────────────────────────────
INFERENCE_JSON = Path("visualize_results/inference_results.json")
IMAGES_DIR     = Path("visualize_results/images")
OUT_DIR        = Path("gemini_results")
GEMINI_MODEL   = "gemini-3-flash-preview"
# Seconds to wait between API calls to avoid rate limiting
API_DELAY      = 1.0

SYSTEM_PROMPT = (
    "You are a professional food analysis assistant. "
    "When given a photo of food, analyze it and return a JSON object with the following fields: "
    "dish_name, food_type, cooking_method, ingredients (list), "
    "portion_size (list of 'item:weight'), and nutritional_profile "
    "(calories_kcal, protein_g, fat_g, carbohydrate_g). "
    "Output only valid JSON, no extra text."
)


# ── Gemini inference ──────────────────────────────────────────────────────────
def call_gemini(model, img_path: Path, retries: int = 3) -> dict:
    image_data = img_path.read_bytes()
    suffix = img_path.suffix.lower()
    mime = {"jpg": "image/jpeg", "jpeg": "image/jpeg", "png": "image/png", "webp": "image/webp"}.get(suffix[1:], "image/jpeg")

    for attempt in range(retries):
        try:
            response = model.generate_content([
                {"mime_type": mime, "data": image_data},
                SYSTEM_PROMPT + "\nAnalyze this food image and return the structured JSON.",
            ])
            text = response.text.strip()
            # Strip markdown code fences if present
            if text.startswith("```"):
                text = text.split("```")[1]
                if text.startswith("json"):
                    text = text[4:]
            return json.loads(text.strip())
        except json.JSONDecodeError:
            return {}
        except Exception as e:
            if attempt < retries - 1:
                time.sleep(2 ** attempt)
            else:
                print(f"  [warn] Gemini failed on {img_path.name}: {e}")
                return {"__failed__": True}


# ── Metrics ───────────────────────────────────────────────────────────────────
def str_sim(a: str, b: str) -> float:
    return SequenceMatcher(None, str(a).lower().strip(), str(b).lower().strip()).ratio()


def ingredients_jaccard(pred_list, gt_str) -> float:
    try:
        gt_list = json.loads(gt_str) if isinstance(gt_str, str) else gt_str
    except Exception:
        return 0.0
    pred_set = {x.lower().strip() for x in pred_list} if isinstance(pred_list, list) else set()
    gt_set   = {x.lower().strip() for x in gt_list}   if isinstance(gt_list, list)  else set()
    if not pred_set and not gt_set:
        return 1.0
    if not pred_set or not gt_set:
        return 0.0
    return len(pred_set & gt_set) / len(pred_set | gt_set)


def compute_metrics(preds: list[dict], gts: list[dict]) -> dict:
    dish, food_type, cook, ingr = [], [], [], []
    cal_preds, cal_gts = [], []

    for pred, gt in zip(preds, gts):
        dish.append(str_sim(pred.get("dish_name", ""), gt.get("dish_name", "")))
        food_type.append(1.0 if pred.get("food_type", "").strip() == gt.get("food_type", "").strip() else 0.0)
        cook.append(str_sim(pred.get("cooking_method", ""), gt.get("cooking_method", "")))
        ingr.append(ingredients_jaccard(pred.get("ingredients", []), gt.get("ingredients", "[]")))

        try:
            nutr_gt = gt.get("nutritional_profile", "{}")
            if isinstance(nutr_gt, str):
                nutr_gt = json.loads(nutr_gt)
            gt_cal   = float(nutr_gt.get("calories_kcal", 0))
            pred_cal = float(pred.get("nutritional_profile", {}).get("calories_kcal", 0))
            if gt_cal > 0 and pred_cal > 0:
                cal_gts.append(gt_cal)
                cal_preds.append(pred_cal)
        except Exception:
            pass

    return {
        "dish_name":      sum(dish)      / len(dish),
        "food_type":      sum(food_type) / len(food_type),
        "cooking_method": sum(cook)      / len(cook),
        "ingredients":    sum(ingr)      / len(ingr),
        "cal_preds": cal_preds,
        "cal_gts":   cal_gts,
    }


# ── Plots ─────────────────────────────────────────────────────────────────────
COLORS = {
    "Base Qwen":    "#5B9BD5",
    "Fine-tuned Qwen": "#ED7D31",
    "Gemini Flash": "#70AD47",
}

def plot_field_accuracy(all_metrics: dict[str, dict]):
    fields = ["dish_name", "food_type", "cooking_method", "ingredients"]
    labels = ["Dish Name\n(similarity)", "Food Type\n(exact)", "Cooking Method\n(similarity)", "Ingredients\n(Jaccard)"]
    n = len(all_metrics)
    width = 0.7 / n
    x = list(range(len(fields)))

    fig, ax = plt.subplots(figsize=(12, 6))
    for idx, (model_name, metrics) in enumerate(all_metrics.items()):
        vals = [metrics[f] * 100 for f in fields]
        offset = (idx - n / 2 + 0.5) * width
        bars = ax.bar([xi + offset for xi in x], vals, width=width,
                      label=model_name, color=COLORS[model_name])
        ax.bar_label(bars, fmt="%.1f%%", padding=3, fontsize=8)

    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=11)
    ax.set_ylabel("Score (%)", fontsize=12)
    ax.set_ylim(0, 120)
    ax.set_title("Field-level Prediction Accuracy: 3-way Comparison", fontsize=14)
    ax.legend(fontsize=11)
    ax.grid(axis="y", alpha=0.3)

    path = OUT_DIR / "field_accuracy_3way.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {path}")


def plot_calorie_scatter(all_metrics: dict[str, dict]):
    n = len(all_metrics)
    fig, axes = plt.subplots(1, n, figsize=(7 * n, 6))
    if n == 1:
        axes = [axes]

    for ax, (model_name, metrics) in zip(axes, all_metrics.items()):
        gts, preds = metrics["cal_gts"], metrics["cal_preds"]
        if not gts:
            ax.set_title(f"{model_name} — no data")
            continue
        max_val = max(max(gts), max(preds)) * 1.1
        ax.scatter(gts, preds, alpha=0.5, color=COLORS[model_name], s=40)
        ax.plot([0, max_val], [0, max_val], "k--", linewidth=1, label="Perfect")
        ax.plot([0, max_val], [0, max_val * 1.2], "r:", linewidth=1, alpha=0.5)
        ax.plot([0, max_val], [0, max_val * 0.8], "r:", linewidth=1, alpha=0.5, label="±20%")
        errors = [abs(p - g) / g * 100 for p, g in zip(preds, gts) if g > 0]
        within = sum(1 for e in errors if e <= 20) / len(errors) * 100
        ax.text(0.05, 0.92, f"Within ±20%: {within:.1f}%", transform=ax.transAxes,
                fontsize=10, bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.5))
        ax.set_xlabel("Ground Truth (kcal)")
        ax.set_ylabel("Predicted (kcal)")
        ax.set_title(model_name, fontsize=13)
        ax.legend(fontsize=9)
        ax.grid(alpha=0.3)

    fig.suptitle("Calorie Prediction Comparison", fontsize=14)
    path = OUT_DIR / "calorie_scatter_3way.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {path}")


def plot_overall_bar(all_metrics: dict[str, dict]):
    """Single bar chart with overall average score per model."""
    fields = ["dish_name", "food_type", "cooking_method", "ingredients"]
    model_names = list(all_metrics.keys())
    avg_scores  = [sum(all_metrics[m][f] for f in fields) / len(fields) * 100 for m in model_names]
    colors      = [COLORS[m] for m in model_names]

    fig, ax = plt.subplots(figsize=(8, 5))
    bars = ax.bar(model_names, avg_scores, color=colors, width=0.5)
    ax.bar_label(bars, fmt="%.1f%%", padding=4, fontsize=12)
    ax.set_ylabel("Average Score (%)", fontsize=12)
    ax.set_ylim(0, 110)
    ax.set_title("Overall Average Score: 3-way Comparison", fontsize=14)
    ax.grid(axis="y", alpha=0.3)

    path = OUT_DIR / "overall_score.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {path}")


# ── Main ─────────────────────────────────────────────────────────────────────
def main():
    OUT_DIR.mkdir(exist_ok=True)

    api_key = os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        raise ValueError("Set GEMINI_API_KEY environment variable first.")
    genai.configure(api_key=api_key)
    gemini = genai.GenerativeModel(GEMINI_MODEL)

    # Load existing Qwen results
    data = json.loads(INFERENCE_JSON.read_text())
    print(f"Loaded {len(data)} samples from {INFERENCE_JSON}\n")

    gts        = [d["ground_truth"]  for d in data]
    base_preds = [d["base_pred"]     for d in data]
    ft_preds   = [d["finetuned_pred"]for d in data]

    # Run Gemini inference — resume if partially done
    gemini_cache = OUT_DIR / "gemini_results.json"
    if gemini_cache.exists():
        gemini_out = json.loads(gemini_cache.read_text())
        done_images = {r["image"] for r in gemini_out}
        print(f"Resuming: {len(done_images)}/{len(data)} already done.")
    else:
        gemini_out = []
        done_images = set()

    print(f"Running Gemini ({GEMINI_MODEL}) inference ...")
    for d in tqdm(data, desc="Gemini"):
        # Re-try previously failed samples
        if d["image"] in done_images:
            existing = next(r for r in gemini_out if r["image"] == d["image"])
            if not existing["gemini_pred"].get("__failed__"):
                continue
            gemini_out.remove(existing)
            done_images.discard(d["image"])
        img_path = IMAGES_DIR / d["image"]
        t0 = time.time()
        pred = call_gemini(gemini, img_path)
        inference_ms = round((time.time() - t0) * 1000, 1)
        gemini_out.append({
            "image": d["image"],
            "ground_truth": d["ground_truth"],
            "gemini_pred": pred,
            "gemini_inference_ms": inference_ms,
        })
        # Save after every sample
        gemini_cache.write_text(json.dumps(gemini_out, indent=2, ensure_ascii=False))
        time.sleep(API_DELAY)

    failed = sum(1 for r in gemini_out if r["gemini_pred"].get("__failed__"))
    if failed:
        print(f"  [warn] {failed} samples failed after retries, excluded from metrics.")
    gemini_out_valid = [r for r in gemini_out if not r["gemini_pred"].get("__failed__")]
    gemini_preds = [r["gemini_pred"] for r in gemini_out_valid]
    gts = [r["ground_truth"] for r in gemini_out_valid]
    base_preds = [base_preds[i] for i, d in enumerate(data) if not gemini_out[i]["gemini_pred"].get("__failed__")]
    ft_preds   = [ft_preds[i]   for i, d in enumerate(data) if not gemini_out[i]["gemini_pred"].get("__failed__")]
    print(f"Gemini results saved to {gemini_cache}")

    # Compute metrics
    all_metrics = {
        "Base Qwen":       compute_metrics(base_preds, gts),
        "Fine-tuned Qwen": compute_metrics(ft_preds,  gts),
        "Gemini Flash":    compute_metrics(gemini_preds, gts),
    }

    # Save summary
    summary = {
        model: {k: v for k, v in m.items() if not isinstance(v, list)}
        for model, m in all_metrics.items()
    }
    (OUT_DIR / "metrics_3way.json").write_text(json.dumps(summary, indent=2))
    print(f"Metrics saved to {OUT_DIR}/metrics_3way.json")

    # Print summary table
    print("\n" + "="*55)
    print(f"{'Metric':<22} {'Base Qwen':>10} {'Fine-tuned':>10} {'Gemini':>10}")
    print("="*55)
    for field in ["dish_name", "food_type", "cooking_method", "ingredients"]:
        row = f"{field:<22}"
        for m in all_metrics.values():
            row += f"{m[field]*100:>9.1f}%"
        print(row)
    print("="*55)

    # Plot
    print("\nGenerating plots ...")
    plot_field_accuracy(all_metrics)
    plot_calorie_scatter(all_metrics)
    plot_overall_bar(all_metrics)

    print(f"\nAll results saved to {OUT_DIR}/")


if __name__ == "__main__":
    main()
